creating Team section+styling it
GSG-FC02/E-commerce-group2-project pull request #14
Opened 2021-03-02 08:43 UTC by Ibrahim-Jarada

Relates #6

2021-03-02 19:01 UTC, sara219 requested changes
solve the conflict

2021-03-02 19:59 UTC, ahmedhamouda2 approved these changes, later dismissed

2021-03-02 20:10 UTC, sara219 requested changes

2021-03-02 20:10 UTC, sara219 commented on index.html
> +              <img class="team-images" src="./img/team/ibrahim.jpg" alt="Ibrahim Jarada">
the image didn't appear correctly 
you write `ibrahim`, and the image saved as `Ibrahim`

2021-03-02 20:10 UTC, sara219 commented on index.html
> +                <img class="team-images" src="./img/team/ola.jpg" alt="Ola Ahel">
same goes here
`Ola` not `ola`

2021-03-02 20:10 UTC, sara219 commented on index.css
> +    /* flex-direction: column; */
delete it if you don't want it

2021-03-02 20:10 UTC, sara219 commented on index.css
> + /* Ibrahim ============================================ */
add descriptive comment 

> our team section style

2021-03-02 20:10 UTC, sara219 commented on index.html
> +     <section class="team-section">
add a comment, a descriptive one to tell us what's that section

2021-03-02 20:42 UTC, sara219 approved these changes

2021-03-02 21:56 UTC, ahmedhamouda2 approved these changes

2021-03-03 05:10 UTC, Ola014 approved these changes

2021-03-03 05:10 UTC, merged