This is my code for the header-nav
GSG-FC02/E-commerce-group2-project pull request #9
Opened 2021-03-01 15:41 UTC by Ola014

Relates #2

2021-03-01 18:22 UTC, sara219 requested changes

2021-03-01 18:22 UTC, sara219 commented on index.html
> +              <li><a href="./index.html">Home</a></li>
You already have a folder for images, why you put it in the same location as the file.

Move all images to the specified folder

2021-03-01 18:22 UTC, sara219 commented on index.css
> +        }
missing closing **`}`** for the media query

2021-03-01 18:22 UTC, sara219 commented on index.css
> +    color:#71585b;
the shadow colour make the hover uncomfortable to look at, try to remove it or chose sth else 
![Screenshot from 2021-03-01 20-01-42](https://user-images.githubusercontent.com/47992412/109539315-d7a71a80-7ac9-11eb-8aca-99e482869e6a.png)

2021-03-01 18:22 UTC, sara219 commented on index.css
> +    font-family: Arial, Helvetica, sans-serif;
this font family didn't change anything from the default one, import it from [google font  ](https://fonts.google.com/)

2021-03-01 18:22 UTC, sara219 commented on index.css
> +    height: 600px;
Why did you add the showcase here even though this is a header section?!!

Delete it from here,
you should add everything in its particular section.

2021-03-01 18:22 UTC, sara219 commented on index.css
> +}
repeated code ( the header above), and also not related to the header section #2

2021-03-02 08:56 UTC, Ola014 commented on index.css
> +    font-family: Arial, Helvetica, sans-serif;
Ok . I will remove the font family. Arial is good font that is convenient for website design,

2021-03-02 08:56 UTC, Ola014 commented on index.css
> +}
That's a mistake from me, I will remove it.

2021-03-02 08:56 UTC, Ola014 commented on index.css
> +    height: 600px;
This is a background image for both header-nav and showcase section. I can not delete it.

2021-03-02 08:58 UTC, Ola014 commented on index.css
> +    font-family: Arial, Helvetica, sans-serif;
This is a convenient font family for this website design.

2021-03-02 09:55 UTC, sara219 approved these changes

2021-03-02 09:56 UTC, Ibrahim-Jarada approved these changes

2021-03-02 09:57 UTC, ahmedhamouda2 approved these changes

2021-03-02 09:58 UTC, merged